const themes = [
    { name: "3024 Day", theme: "3024-day" },
    { name: "3024 Night", theme: "3024-night" },
    { name: "ABCDEF", theme: "abcdef" },
    { name: "Ambiance Mobile", theme: "ambiance-mobile" },
    { name: "Ambiance", theme: "ambiance" },
    { name: "Ayu Dark", theme: "ayu-dark" },
    { name: "Ayu Mirage", theme: "ayu-mirage" },
    { name: "Base16 Dark", theme: "base16-dark" },
    { name: "Base16 Light", theme: "base16-light" },
    { name: "Bespin", theme: "bespin" },
    { name: "Blackboard", theme: "blackboard" },
    { name: "Cobalt", theme: "cobalt" },
    { name: "Colorforth", theme: "colorforth" },
    { name: "Darcula", theme: "darcula" },
    { name: "Duotone Dark", theme: "duotone-dark" },
    { name: "Duotone Light", theme: "duotone-light" },
    { name: "Eclipse", theme: "eclipse" },
    { name: "Elegant", theme: "elegant" },
    { name: "Erlang Dark", theme: "erlang-dark" },
    { name: "Gruvbox Dark", theme: "gruvbox-dark" },
    { name: "Hopscotch", theme: "hopscotch" },
    { name: "Icecoder", theme: "icecoder" },
    { name: "Idea", theme: "idea" },
    { name: "Isotope", theme: "isotope" },
    { name: "Lesser Dark", theme: "lesser-dark" },
    { name: "Liquibyte", theme: "liquibyte" },
    { name: "Lucario", theme: "lucario" },
    { name: "Material Darker", theme: "material-darker" },
    { name: "Material Ocean", theme: "material-ocean" },
    { name: "Material Palenight", theme: "material-palenight" },
    { name: "Material", theme: "material" },
    { name: "Mbo", theme: "mbo" },
    { name: "MDN Like", theme: "mdn-like" },
    { name: "Midnight", theme: "midnight" },
    { name: "Monokai", theme: "monokai" },
    { name: "Moxer", theme: "moxer" },
    { name: "Neat", theme: "neat" },
    { name: "Neo", theme: "neo" },
    { name: "Night", theme: "night" },
    { name: "Nord", theme: "nord" },
    { name: "Oceanic Next", theme: "oceanic-next" },
    { name: "Panda Syntax", theme: "panda-syntax" },
    { name: "Paraiso Dark", theme: "paraiso-dark" },
    { name: "Paraiso Light", theme: "paraiso-light" },
    { name: "Pastel on Dark", theme: "pastel-on-dark" },
    { name: "Railscasts", theme: "railscasts" },
    { name: "Rubyblue", theme: "rubyblue" },
    { name: "Seti", theme: "seti" },
    { name: "Shadowfox", theme: "shadowfox" },
    { name: "Solarized", theme: "solarized" },
    { name: "SSMS", theme: "ssms" },
    { name: "The Matrix", theme: "the-matrix" },
    { name: "Tomorrow Night Bright", theme: "tomorrow-night-bright" },
    { name: "Tomorrow Night Eighties", theme: "tomorrow-night-eighties" },
    { name: "TTCN", theme: "ttcn" },
    { name: "Twilight", theme: "twilight" },
    { name: "Vibrant Ink", theme: "vibrant-ink" },
    { name: "XQ Dark", theme: "xq-dark" },
    { name: "XQ Light", theme: "xq-light" },
    { name: "Yeti", theme: "yeti" },
    { name: "Yonce", theme: "yonce" },
    { name: "Zenburn", theme: "zenburn" },
];


export default themes;